[tool.black]
# Maximum line length for code formatting.
# Set to 88 by default.
line-length = 88

# Maximum length of consecutive lines before they are broken up.
# Set to 88 by default.
max-line-length = 88

# Minimum number of consecutive lines to break into chunks.
# Set to 1 by default.
min-string-paragraphs = 1

# Whether to normalize string literals to use single or double quotes.
# Possible values: 'true', 'false'.
# Set to 'true' by default.
string-normalization = "true"

# Whether to skip normalizing string literals.
# Possible values: 'true', 'false'.
# Set to 'false' by default.
skip-string-normalization = false

# Whether to put closing brackets/braces/parentheses on a new line.
# Possible values: 'true', 'false'.
# Set to 'false' by default.
experimental-string-processing = false

# Indentation width to use.
# Set to 2 spaces by default.
indent = 2
